export const GET_STACKOVERFLOW_PAGE_REQUEST = 'stack/GET_STACKOVERFLOW_PAGE_REQUEST'
export const GET_STACKOVERFLOW_PAGE_SUCCESS = 'stack/GET_STACKOVERFLOW_PAGE_SUCCESS'
export const GET_STACKOVERFLOW_PAGE_FAIL = 'stack/GET_STACKOVERFLOW_PAGE_FAIL'

export const PROCEED_STACKOVERFLOW_DATA = 'stack/PROCEED_STACKOVERFLOW_DATA'
export const FLUSH_STACKOVERFLOW_DATA = 'stack/FLUSH_STACKOVERFLOW_DATA'
